stages:
  - build
  - test

build_job:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet restore
    - dotnet build --no-restore
  only:
    - master

test_job:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet restore
    - dotnet test --no-restore --verbosity normal
  only:
    - master
