using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TFYP.Model.Facilities;
using TFYP.Model.City;
using TFYP.Model.Zones;
using ProtoBuf;

namespace TFYP.Model.Common
{
    [ProtoContract]
    [Serializable]
    public class Budget
    {


        [ProtoMember(1)]
        public double Balance { get; set; }
        [ProtoMember(2)]
        public int CurrentTax { get; set; }
        [ProtoMember(3)]
        public float CurrentTaxRate { get; set; }
        [ProtoMember(4)]
        public double MaintenanceFeeForEverything { get; set; }
        [ProtoMember(5)]
        public DateTime DateOfStartingLoan { get; set; }

        public Budget()
        {
            Balance = Constants.InitialBalance;
            CurrentTax = Constants.CityBaseTax;
            CurrentTaxRate = Constants.CityBaseTaxRate;
            MaintenanceFeeForEverything = 0;
            DateOfStartingLoan = DateTime.MinValue;
        }

        /// <summary>
        /// Updates the balance of the budget by the specified amount and tracks the date when the balance goes below zero.
        /// </summary>
        /// <param name="amount">The amount to update the balance by.</param>
        /// <param name="gameTime">The current game time.</param>

        public void UpdateBalance(double amount, DateTime gameTime)
        {
            Balance += amount;
            if (Balance < 0)
            {
                DateOfStartingLoan = gameTime;
            }
        }

        /// <summary>
        /// Calculates the number of years the budget has been in a loan since the starting date of the loan until the specified game time.
        /// </summary>
        /// <param name="gameTime">The current game time.</param>
        /// <returns>The number of years the budget has been in a loan.</returns>

        public int YearsOfBeingInLoan(DateTime gameTime)
        {
            if(DateOfStartingLoan != DateTime.MinValue && gameTime > DateOfStartingLoan)
            {
                return gameTime.Year - DateOfStartingLoan.Year - (gameTime.DayOfYear < DateOfStartingLoan.DayOfYear ? 1 : 0);
            }
            return 0;
        }

        public void AddToMaintenanceFee(double maintenanceFee)
        {
            MaintenanceFeeForEverything += maintenanceFee;
        }

        public void RemoveFromMaintenanceFee(double maintenanceFee)
        {
            MaintenanceFeeForEverything -= maintenanceFee;
        }

        /// <summary>
        /// Computes the total revenue generated by active citizens residing in residential zones.
        /// </summary>
        /// <param name="gm">The GameModel instance containing the city registry.</param>
        /// <returns>The total revenue generated.</returns>

        public double ComputeRevenue(GameModel gm)
        {
            // Sum the TaxAmount for only active citizens
            double revenue = 0;

            foreach (var residentialZone in gm.CityRegistry.Zones.Where(z => z.Type == EBuildable.Residential))
            {
                revenue += residentialZone.citizens.Where(citizen => citizen.IsActive).Sum(citizen => citizen.TaxAmount(this));
            }
            return revenue;
        
        }


    }
}
